"""add body_html

Revision ID: 387bd5574b6b
Revises: None
Create Date: 2016-05-07 16:55:29.409058

"""

# revision identifiers, used by Alembic.
revision = '387bd5574b6b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.drop_column('posts', 'summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', mysql.TEXT(), nullable=True))
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
